#!/bin/bash

# Colors
color_green='\u001b[32m'
color_underline_green='\033[4;32m'
color_underline_red='\033[4;31m'
color_underline_yellow='\033[4;33m'
color_background_green='\033[42m'
color_background_red='\033[41m'
color_reset='\033[0m'

# Intro
printf "Starting checks on ${color_underline_yellow}commit${color_reset} command with ${color_underline_yellow}git hooks${color_reset}.\n"

git stash -S -m "Automatic stash for staged files." > /dev/null 2>&1
git stash -u -m "Stashing everything else including untracked files." > /dev/null 2>&1

# Recovering only the staged files. When there's only one stash we use 0. If there are more
# it's always the number 1.
if [ $(git stash list | wc -l) -eq 1 ]; then
    git stash pop --index 0  > /dev/null 2>&1
else
    git stash pop --index 1 > /dev/null 2>&1
fi

###############
# Typescript
###############
printf "\n${color_underline_green}Typescript${color_reset} analysis (static code analysis).\n\n"

if ! sudoDockerReplace exec -t appNameReplace npm run ts; then
    printf "  ╭──────────────────────────────────────────────────────────────────────────╮  "
    printf "\n  | ${color_background_red}GIT COMMIT STOPPED${color_reset} ✋                                                    | "
    printf "\n  |                                                                          |  "
    printf "\n  |           ${color_background_red}Typescript analysis failed.${color_reset} You have ${color_underline_yellow}problems${color_reset} on your code.  | "
    printf "\n  |                                                                          |  \n"
    printf "  ╰──────────────────────────────────────────────────────────────────────────╯  \n"

    git stash pop > /dev/null 2>&1  # Reverting the everything else stash.

    exit 1
fi

###############
# ESLint
###############
printf "\n${color_underline_green}ESLint${color_reset} analysis (formatter + static code analysis).\n\n"

if ! sudoDockerReplace exec -t appNameReplace npm run lint:fix; then
    printf "  ╭──────────────────────────────────────────────────────────────────────────╮  "
    printf "\n  | ${color_background_red}GIT COMMIT STOPPED${color_reset} ✋                                                    | "
    printf "\n  |                                                                          |  "
    printf "\n  |           ${color_background_red}ESLint analysis failed.${color_reset} You have ${color_underline_yellow}problems${color_reset} on your code.        | "
    printf "\n  |                                                                          |  \n"
    printf "  ╰──────────────────────────────────────────────────────────────────────────╯  \n"

    git add . > /dev/null 2>&1      # Adding the new ESLint changes.
    git stash pop > /dev/null 2>&1  # Reverting the everything else stash.

    exit 1
fi

# Everything went well. Adding the new ESLint changes and reverting the stash.
git add . > /dev/null 2>&1     # Adding the new ESLint changes.
git stash pop > /dev/null 2>&1 # Reverting the everything else stash.

###############
# Final success message
###############
printf "  ╭──────────────────────────────────────────────────────────────────────────╮  "
printf "\n  | ${color_background_green}GIT COMMIT SUCCESSFUL${color_reset} ✅                                                 | "
printf "\n  |                                                                          |  "
printf "\n  |               ${color_background_green}Thank you traveler.${color_reset} Push to ship 🚀.                       |  "
printf "\n  |                                                                          |  \n"
printf "  ╰──────────────────────────────────────────────────────────────────────────╯  \n"
printf "${color_reset}\n"
